# Site settings
title: Rick van Mook | Creative Developer
email: rick@rvmook.com
description: > # this means to ignore newlines until "baseurl:"
  Portoflio of Creative Developer Rick van Mook
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rvmook.com" # the base hostname & protocol for your site
twitter_username: rvmook
github_username:  rvmook

source: src
destination: dist

timezone: America/New_York

# Build settings
markdown: kramdown
